import { addDays, todaySA } from "./dates";
import type { Resource } from "./types";

// Sample inventory used by `npm run seed` and by the in-memory dev store.
// Replace with Z Studios' real list and rates before launch.
// Images: see src/lib/images.ts for sources/licences — swap for Zstudio's own shots when available.
type SeedResource = Omit<Resource, "images"> & { images?: string[] };

const seed: SeedResource[] = [
  {
    id: "studio-main",
    kind: "studio",
    slug: "the-studio",
    name: "The Studio",
    category: "Studio",
    description:
      "A blacked-out, fully controllable space for photoshoots, podcasts, music videos and headshots. Booked by the full day, with house backdrops and grip included.",
    specs: [
      "Full-day hire, 08:00–20:00",
      "Seamless paper backdrops (black, white, grey)",
      "C-stands, sandbags and grip included",
      "Blackout control, power on all walls",
      "Make-up station and client lounge",
    ],
    dailyRate: 3500,
    stock: 1,
    active: true,
    sortOrder: 0,
  },
  {
    id: "sony-fx3",
    images: ["/equipment/sony-fx3.jpg"],
    kind: "equipment",
    slug: "sony-fx3",
    name: "Sony FX3",
    category: "Cameras",
    description: "Full-frame cinema line body. Compact, dual base ISO, 4K 120p.",
    specs: ["Full-frame 12.1MP", "4K up to 120p", "S-Cinetone / S-Log3", "2× CFexpress Type A"],
    dailyRate: 1250,
    stock: 2,
    active: true,
    sortOrder: 10,
  },
  {
    id: "sony-a7siii",
    images: ["/equipment/sony-a7siii.jpg"],
    kind: "equipment",
    slug: "sony-a7s-iii",
    name: "Sony A7S III",
    category: "Cameras",
    description: "Low-light hybrid body for video-first shooters.",
    specs: ["Full-frame 12.1MP", "4K up to 120p", "10-bit 4:2:2", "Fully articulating screen"],
    dailyRate: 950,
    stock: 1,
    active: true,
    sortOrder: 11,
  },
  {
    id: "sigma-24-70",
    images: ["/equipment/sigma-24-70.jpg"],
    kind: "equipment",
    slug: "sigma-24-70-f2-8",
    name: "Sigma 24–70mm f/2.8 DG DN Art",
    category: "Lenses",
    description: "Workhorse standard zoom, E-mount.",
    specs: ["E-mount", "f/2.8 constant", "82mm filter thread"],
    dailyRate: 400,
    stock: 2,
    active: true,
    sortOrder: 20,
  },
  {
    id: "aputure-600d",
    images: ["/equipment/aputure-600d-pro.png"],
    kind: "equipment",
    slug: "aputure-ls-600d-pro",
    name: "Aputure LS 600d Pro",
    category: "Lighting",
    description: "Daylight COB key light with Bowens mount.",
    specs: ["5600K", "600W", "Bowens mount", "V-mount or mains"],
    dailyRate: 850,
    stock: 2,
    active: true,
    sortOrder: 30,
  },
  {
    id: "amaran-200x",
    images: ["/equipment/amaran-200x.png"],
    kind: "equipment",
    slug: "amaran-200x",
    name: "Amaran 200x",
    category: "Lighting",
    description: "Bi-colour fill light, light enough to rig anywhere.",
    specs: ["2700–6500K", "200W", "Bowens mount"],
    dailyRate: 350,
    stock: 4,
    active: true,
    sortOrder: 31,
  },
  {
    id: "softbox-120",
    images: ["/equipment/light-dome.png"],
    kind: "equipment",
    slug: "light-dome-120",
    name: "Light Dome 120cm",
    category: "Lighting",
    description: "Deep parabolic softbox with grid for soft, controlled key light.",
    specs: ["120cm", "Bowens mount", "Fabric grid included"],
    dailyRate: 200,
    stock: 3,
    active: true,
    sortOrder: 32,
  },
  {
    id: "backdrop-paper",
    images: ["/equipment/backdrop-paper.jpg"],
    kind: "equipment",
    slug: "seamless-paper-backdrop",
    name: "Seamless Paper Backdrop Kit",
    category: "Backdrops",
    description: "2.72m paper roll with stands and crossbar. Choose colour on collection.",
    specs: ["2.72m × 11m", "Stands + crossbar", "Black, white, grey, rose"],
    dailyRate: 250,
    stock: 3,
    active: true,
    sortOrder: 40,
  },
  {
    id: "rode-podmic-kit",
    images: ["/equipment/rodecaster-pro.jpg","/equipment/rode-podmic.png"],
    kind: "equipment",
    slug: "rode-podcast-kit",
    name: "Rode Podcast Kit (2 mics)",
    category: "Audio",
    description: "Two PodMics, boom arms and a RødeCaster for a ready-to-go podcast set.",
    specs: ["2× Rode PodMic", "2× PSA1 boom arms", "RødeCaster Pro II"],
    dailyRate: 600,
    stock: 1,
    active: true,
    sortOrder: 50,
  },
  {
    id: "dji-rs4",
    images: ["/equipment/dji-rs4.png"],
    kind: "equipment",
    slug: "dji-rs-4",
    name: "DJI RS 4",
    category: "Support",
    description: "3-axis gimbal for mirrorless bodies up to 3kg.",
    specs: ["3kg payload", "Native vertical shooting", "Bluetooth shutter"],
    dailyRate: 450,
    stock: 2,
    active: true,
    sortOrder: 60,
  },
  // SAMPLE workshop so the community page has something to show in development.
  // Not a real event — replace with Zstudio's actual workshops (or delete) before launch.
  {
    id: "workshop-sample-lighting",
    kind: "workshop",
    slug: "studio-lighting-basics",
    name: "Studio Lighting Basics (sample)",
    category: "Workshop",
    description:
      "SAMPLE LISTING — replace with a real workshop. A hands-on morning on key, fill and rim light using the studio's own kit.",
    specs: ["Hands-on with studio lighting", "Small group", "Bring your own camera"],
    dailyRate: 650,
    stock: 12,
    active: true,
    sortOrder: 100,
    date: addDays(todaySA(), 21),
    startTime: "10:00",
    endTime: "13:00",
    host: "Z Studios",
  },
];

export const seedResources: Resource[] = seed.map((r) => ({ images: [], ...r }));
