import { addDays, todaySA } from "./dates";
import { equipment } from "./equipment-data";
import { PRODUCTION_TEAM_ID, type Resource } from "./types";

// Inventory used by `npm run seed` and by the in-memory dev store.
// Studio spaces and equipment are the client's real list and rates.
type SeedResource = Omit<Resource, "images"> & { images?: string[] };

const seed: SeedResource[] = [
  // Studio spaces, from the client's brochure (October 2026). dailyRate is the 30-minute rate.
  {
    id: "podcast-studio",
    images: ["/studio/podcast-room.jpg"],
    kind: "studio",
    slug: "podcast-studio",
    name: "Podcast Studio",
    category: "Studio",
    description: "A fully equipped podcast studio designed for high-quality audio and video content.",
    specs: ["RØDE podcasting setup", "Wireless microphones", "Video and sound mixers", "Promo rate"],
    dailyRate: 1000,
    stock: 1,
    active: true,
    sortOrder: 0,
  },
  {
    id: "white-studio",
    images: ["/studio/cyclorama.jpg"],
    kind: "studio",
    slug: "white-studio",
    name: "White Studio",
    category: "Studio",
    description: "A clean, professional infinity wall, perfect for photography, product shoots and more.",
    specs: ["White infinity cove", "Photography, product shoots, content"],
    dailyRate: 400,
    stock: 1,
    active: true,
    sortOrder: 1,
  },
  {
    id: "green-screen-studio",
    images: ["/studio/green-screen.jpg", "/studio/cyclorama-green-screen.jpg"],
    kind: "studio",
    slug: "green-screen-studio",
    name: "Green Screen Studio",
    category: "Studio",
    description: "A fully functional green screen studio for video productions, interviews, ads and more.",
    specs: ["Chroma-key green cove", "Video productions, interviews, ads"],
    dailyRate: 400,
    stock: 1,
    active: true,
    sortOrder: 2,
  },
  {
    id: "boardroom",
    images: ["/studio/meeting-room.jpg"],
    kind: "studio",
    slug: "boardroom",
    name: "Boardroom",
    category: "Studio",
    description: "A modern, professional meeting space for teams and clients.",
    specs: ["Conference table and seating", "Minimum booking: 1 hour"],
    dailyRate: 150,
    minSlots: 2,
    stock: 1,
    active: true,
    sortOrder: 3,
  },
  // Production services, from the client's brochure. Each booking holds the production team and,
  // indoors, a studio room, so neither is double-booked. dailyRate = the cheapest package.
  {
    id: "music-video",
    images: ["/studio/green-screen.jpg"],
    kind: "service",
    slug: "music-video-production",
    name: "Music Video Production",
    category: "Production",
    description: "Our team shoots, edits and colour grades your music video, in the studio or on location.",
    specs: ["Shooting", "Editing", "Colour grading"],
    dailyRate: 5000,
    stock: 1,
    active: true,
    sortOrder: 10,
    packages: [
      { id: "indoor-4h", label: "4-hour indoor shoot", slots: 8, price: 5000, location: "studio" },
      { id: "outdoor-4h", label: "4-hour outdoor shoot", slots: 8, price: 10000, location: "outdoor" },
    ],
    rooms: ["white-studio", "green-screen-studio"],
  },
  {
    id: "photoshoots",
    images: ["/studio/cyclorama.jpg"],
    kind: "service",
    slug: "photoshoots",
    name: "Photoshoots",
    category: "Production",
    description: "A photoshoot in the White Studio with our photographer.",
    specs: ["Shot in the White Studio", "Edited selects"],
    dailyRate: 1000,
    stock: 1,
    active: true,
    sortOrder: 11,
    packages: [
      { id: "30-min", label: "30 minutes", slots: 1, price: 1000, location: "studio" },
      { id: "1-hour", label: "1 hour", slots: 2, price: 2000, location: "studio" },
    ],
    rooms: ["white-studio"],
  },
  {
    id: "headshots",
    images: ["/studio/cyclorama.jpg"],
    kind: "service",
    slug: "headshots",
    name: "Headshots",
    category: "Production",
    description: "Professional headshots in our studio, 30 minutes per person. Negotiable for groups.",
    specs: ["30 minutes per person", "Groups of 5+: contact us"],
    dailyRate: 1000,
    stock: 1,
    active: true,
    sortOrder: 12,
    packages: [{ id: "per-person", label: "30 minutes per person", slots: 1, price: 1000, location: "studio", perPerson: true }],
    rooms: ["white-studio"],
  },
  {
    // Not bookable itself: every service booking holds it. stock = crews that can shoot at once.
    id: PRODUCTION_TEAM_ID,
    kind: "service",
    slug: "production-team",
    name: "Production team",
    category: "Team",
    description: "Held by every production booking so the crew is never double-booked.",
    specs: [],
    dailyRate: 0,
    stock: 1,
    active: true,
    sortOrder: 19,
    packages: [],
  },
  ...equipment,
  // SAMPLE workshop so the community page has something to show in development.
  // Not a real event — replace with Zstudio's actual workshops (or delete) before launch.
  {
    id: "workshop-sample-lighting",
    kind: "workshop",
    slug: "studio-lighting-basics",
    name: "Studio Lighting Basics (sample)",
    category: "Workshop",
    description:
      "SAMPLE LISTING — replace with a real workshop. A hands-on morning on key, fill and rim light using the studio's own kit.",
    specs: ["Hands-on with studio lighting", "Small group", "Bring your own camera"],
    dailyRate: 650,
    stock: 12,
    active: true,
    sortOrder: 100,
    date: addDays(todaySA(), 21),
    startTime: "10:00",
    endTime: "13:00",
    host: "Z Studios",
  },
];

export const seedResources: Resource[] = seed.map((r) => ({ images: [], ...r }));
