import { existsSync } from "node:fs";
import path from "node:path";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { isDemoMode } from "@/lib/demo";

// Generated by `npm run logo` from Z Studios' logo artwork.
const hasMark = existsSync(path.join(process.cwd(), "public", "brand", "mark.png"));

/** Public site chrome. The admin dashboard (/admin) has its own layout. */
export default function SiteLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      {isDemoMode() && (
        <p className="border-b border-rose/30 bg-rose/10 px-4 py-2 text-center text-xs text-rose">
          Preview site — sample inventory; bookings and sign-ups aren&rsquo;t saved or sent.
        </p>
      )}
      <SiteHeader hasMark={hasMark} />
      <main className="flex-1">{children}</main>
      <SiteFooter />
    </>
  );
}
