import { existsSync } from "node:fs";
import path from "node:path";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";

// Generated by `npm run logo` from Z Studios' logo artwork.
const hasMark = existsSync(path.join(process.cwd(), "public", "brand", "mark.png"));

/** Public site chrome. The admin dashboard (/admin) has its own layout. */
export default function SiteLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <SiteHeader hasMark={hasMark} />
      <main className="flex-1">{children}</main>
      <SiteFooter />
    </>
  );
}
